require("remap")
require("config")
require("lazy-plugin")
-- vim.cmd([[colorscheme tokyonight-night]])
-- vim.cmd([[colorscheme nightfox]])
vim.cmd([[colorscheme carbonfox]])
vim.api.nvim_set_hl(0,"Normal", {bg = "none"})
vim.api.nvim_set_hl(0,"NormalFloat", {bg = "none"})
